baseURL: "https://experimentsofindrajith.in"
languageCode: en-us
title: Experiments of Indrajith
theme: terminal
copyright: Indrajith K L
Description: Personal website of Indrajith K L portraying Game Designs, Web Development and IoT experiments
params:
  themeColor: pink
  logo:
    logoText: Experiments of Indrajith

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
      
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
      
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30

languages:
    en:
      params:
        languageName: English
        title: Experiments of Indrajith
        subtitle: Personal website of Indrajith K L portraying Game Designs, Web Development and IoT experiments
